# Name of your application. Used to uniquely configure containers.
service: demo

# Name of the container image.
image: deanin/kamal-demo

# Deploy to these servers.
servers:
  web:
    hosts:
      - 167.71.178.142
    labels:
      traefik.http.routers.deanout_secure.entrypoints: websecure
      traefik.http.routers.deanout_secure.rule: Host(`deanout.com`)
      traefik.http.routers.deanout_secure.tls: true

# Credentials for your image host.
registry:
  username: deanin
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.websecure.address: ":443"

volumes:
  - "storage:/rails/storage"
